[package]
name = "swayautonames"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
dirs = "5.0.1"
log = "0.4.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
simplelog = "0.12.1"
swayipc = "3.0.1"
